### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by essen** [jlouis/erl-lenses#1]
Eqc is required. Any chance the header file can be included conditionally?

**Comment by jlouis** [comment]
Right, this is a toy project, a prototype if you may. It can't be included in any piece of software as it is. I started doing the `forge` project for this kind of processing, but it also fell short because at the time, I did not have access to maps. Nowadays, I think the right approach is to revive `forge` and ignore this repository.

**Comment by essen** [comment]
Alright, will add forge then. Thanks!
